### ISSUE TITLE
Update the logo

### ISSUE THREAD

**Issue by Neustradamus** [UWPX/uwpx.github.io#1]
I have seen a beautiful logo but the XMPP logo has been updated in 2017, can you update it too?
- Source: https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

**Comment by COM8** [comment]
Yes, thanks!

**Comment by COM8** [comment]
Done.

![600](https://user-images.githubusercontent.com/11741404/51907944-97e04700-23c8-11e9-8398-3223eeaa59b1.png)

**Comment by Neustradamus** [comment]
@COM8: Can you update a new time?

There were 2 changes in the XMPP logo, please look here:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

Old version, there was a problem: https://i.ibb.co/vcqmc8b/xmpp-logo-xsf-test.png

**Comment by COM8** [comment]
I don't think I'm using it any where.
Did you spot the XMPP logo somewhere?

**Comment by Neustradamus** [comment]
Last version is here:
- https://commons.wikimedia.org/wiki/File:XMPP_logo.svg

**Comment by COM8** [comment]
Yes, I know where I can find it (thanks I guess😄).
**But** I'm not aware of any place where I'm using the XMPP logo in my repositories.
So... I don't think I need to update it anywhere 🤷🏻‍♂️.

**Comment by Neustradamus** [comment]
@COM8: Look your previous commit ^^

**Comment by COM8** [comment]
@Neustradamus my "previous" commit was [Increased the image size again](https://github.com/UWPX/uwpx.github.io/commit/50824bbc992eef76dbd405ea3887a733ac0421e4).

I don't get it...
Please, if you spotted a place where I have to update the logo, let me know (LINK!!).
I tired of those pointless conversations where I try to figure out what you want to tell me!

If you want to tell me something, do it in a short pregnant way with **all** the required information.
I'd rather spend this time developing UWPX 😉.

**Comment by Neustradamus** [comment]
You have removed the XMPP logo?
- https://github.com/UWPX/uwpx.github.io/commit/bc2ebc7c32a4eba5f60e4c7877617ad603d4a0f1

**Comment by COM8** [comment]
I changed the logo of UWPX a while ago.
This is the new one:
![](https://raw.githubusercontent.com/UWPX/uwpx.github.io/master/images/logos/uwpx_1500.png)

Hope this is what you were intending ;)

**Comment by Neustradamus** [comment]
It is for this ;)
