### ISSUE TITLE
jabber.org TLS_CONNECTION_FAILED

### ISSUE THREAD

**Issue by m-alice** [UWPX/uwpx.github.io#4]
Maybe certificate issue?
windows 10.0.17763.678 pro
uwpx 0.19.0

**Comment by COM8** [comment]
Is this still an issue?
Can you please try it again.
My server has an IP that changes every day so once it changes there are a few minutes every day where IP and cert do not match.

**Comment by m-alice** [comment]
Sorry, my mistake. When i create new account record in messenger,  in server field for some reason it turned out to be written _hermes2.jabber.org_, i dont' know why. Changed in just _jabber.org_ solved the problem.
